_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/src/models/training/unsw/unswnb15_payload_binary_training_exp.ipynb
        m: []
        python_version: 3.11.7
        session_history: code\_session_history.ipynb
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
architecture:
    value: ViT
dataset:
    value: UNSW-NB15-payload-exp
epochs:
    value: 5
learning_rate:
    value: 0.001
